---
variables:
  P5VER: perl5.38.0
  LOCALPERLBIN: /opt/perl/$P5VER/bin
  LOCALPERLLIB: /opt/perl/$P5VER/local
  PERL5LIB: $LOCALPERLLIB/lib/perl5
  AUTHOR_TESTING: 1

stages:
  - prebuild
  - build
  - test
  - clean

perl-prebuild-job:
  stage: prebuild
  tags: [fidoci]
  script:
    - $LOCALPERLBIN/cpanm --from https://dpan.ztreet.nl/ -L $LOCALPERLLIB --installdeps .

perl-build-job:
  stage: build
  tags: [fidoci]
  script:
    - $LOCALPERLBIN/perl Makefile.PL
    - make
  artifacts:
    paths:
      - Makefile
      - blib/
      - pm_to_blib
      - MYMETA.*

perl-test-job:
  stage: test
  tags: [fidoci]
  dependencies: [perl-build-job]
  script:
    - make test TEST_VERBOSE=1 TEST_FILES=xt/*.t
    - make test TEST_VERBOSE=1

perl-cleanup-job:
  stage: clean
  tags: [fidoci]
  dependencies: [perl-build-job]
  script:
    - make distclean
