---
variables:
  LOCALPERLLIB: /opt/perl/perl5.38.0/local
  PERL5LIB: $LOCALPERLLIB/lib/perl5

stages:
  - prebuild
  - build
  - test
  - clean

perl-prebuild-job:
  stage: prebuild
  tags: [fidoci]
  script:
    - cpanm --from https://dpan.ztreet.nl/ -L $LOCALPERLLIB --installdeps .

perl-build-job:
  stage: build
  tags: [fidoci]
  script:
    - perl Makefile.PL
    - make

perl-test-job:
  stage: test
  tags: [fidoci]
  variables:
    AUTHOR_TESTING: 1
  script:
    - make test TEST_VERBOSE=1

perl-cleanup-job:
  stage: clean
  tags: [fidoci]
  script:
    - make distclean
